FUNCION CELSIUS <- DATO_CELSIUS ()
	Definir CELSIUS Como Real
	Escribir "ESCRIBE LE TEMPERTURA QUE QUIERES PASAR A GRADOS FAHRENHEIT"
	Leer CELSIUS
FinFuncion

Funcion RESULTADO(CEL)
	DEFINIR RESUL Como Real
	RESUL<- (CEL*1.8) + 32
	Escribir " LA TEMPERATURA DE CELSIUS A FAHRENHEIT ES: " RESUL
	
FinFuncion

Algoritmo FUNCIONES_11
	CEL<- DATO_CELSIUS
	
	RESULTADO(CEL)
	
FinAlgoritmo
	