FUNCION KILOGRAMOS <- DATO_KG
	DEFINIR KILOGRAMOS Como Real
	Escribir "CUANTO PESAS (KG)"
	Leer KILOGRAMOS
FinFuncion

FUNCION ALTURA <- DATO_ALTURA 
	DEFINIR ALTURA Como Real
	ESCRIBIR "CUAL ES TU ALTRURA (M)"
	Leer ALTURA 
FinFuncion

FUNCION IMC(KG,M)
	DEFINIR IMC1 Como Real
	IMC1<- KG/(M*M)
	Escribir "ESTE ES TU IMC " IMC1
FinFuncion


Algoritmo FUNCIONES_16
	KG<-DATO_KG
	M<-DATO_ALTURA
	IMC(KG,M)
	
	
FinAlgoritmo
	