Funcion RESP <- PEDIR_RESPUESTA()
	Definir RESP Como Logico
	Escribir 'RESPONDA SI ES ESTUDIANTE (VERDADERO/FALSO)'
	Leer RESP
FinFuncion

Funcion MOSTRAR_RESPUESTA(RESP)
	Si RESP=VERDADERO Entonces
		Escribir 'UD ES ESTUDIANTE'
	SiNo
		Escribir 'UD NO ES ESTUDIANTE'
	FinSi
FinFuncion

Algoritmo FUNCIONES_4
	RESPUESTA <- PEDIR_RESPUESTA()
	MOSTRAR_RESPUESTA(RESPUESTA)
FinAlgoritmo
