FUNCION PRECIO<- DATO_PRECIO
	DEFINIR PRECIO Como Real
	Escribir "ESCRIBE EL PRECIO DEL PRODUCTO"
	Leer PRECIO
FinFuncion

FUNCION RESULTADO_PRECIO (PREC)
	Definir RESULTADODEPAGO Como Real
	RESULTADODEPAGO<- PREC*0.4
	Escribir "ESTE ES TU TOTAL A PAGAR CON DESCUENTO : " RESULTADODEPAGO "$"
FinFuncion


Algoritmo FUNCIONES_9
	PREC<-DATO_PRECIO

	
	RESULTADO_PRECIO(PREC)
	
	
FinAlgoritmo
	