FUNCION RANGO(PISODESEADO)
	SI PISODESEADO>0  Y PISODESEADO<=10 Entonces
		Escribir "LLENDO A PISO " PISODESEADO
	SiNo
		Escribir "ERROR PISO INVALIDO"
	FinSi
FinFuncion

Algoritmo FUCNIONES_SI_SINO2
	Definir PISODESEADO COMO ENTERO
	Escribir "A QUE PISO DESEA IR"
	Leer PISODESEADO
	
RANGO(PISODESEADO)
	
FinAlgoritmo
	