FUNCION RANGO(TEMPERATURADESEADA,UMBRAL )
	SI  TEMPERATURADESEADA<=UMBRAL  Entonces
		Escribir "TEMPERATURA NORMAL"
	SiNo
		Escribir "TEMPERATURA ENCIMA DEL UMBRAL  " 
	FinSi
FinFuncion

Algoritmo FUCNIONES_SI_SINO3
	Definir TEMPERATURADESEADA COMO ENTERO
	DEFINIR UMBRAL Como EnterO

	
	Escribir "ESCRIBRE LA TEMPERATURA ACTUAL "
	Leer TEMPERATURADESEADA
	
	Escribir "INGRESE EL UMBRAL DE ALERTA"
	Leer UMBRAL
	

RANGO(TEMPERATURADESEADA, UMBRAL)
	
FinAlgoritmo
	